skin_map = {
  "Forest Ddpat" : "Forest DDPAT",
  "Orange Ddpat" : "Orange DDPAT",
  "Caution!" : "CAUTION!",
  "Calicamo" : "CaliCamo",
  "Eye Of Athena" : "Eye of Athena",
  "Dev_texture" : "dev_texture",
  "Varicamo Blue" : "VariCamo Blue",
  "Co-processor" : "Co-Processor",
  "Desert Ddpat" : "Desert DDPAT",
  "Xoxo" : "XOXO",
  "Death By Kitty" : "Death by Kitty",
  "Purple Ddpat" : "Purple DDPAT",
  "Urban Ddpat" : "Urban DDPAT",
  "Welcome To The Jungle" : "Welcome to the Jungle",
  "Sun In Leo" : "Sun in Leo",
  "Fizzy Pop" : "Fizzy POP",
  "Varicamo" : "VariCamo",
  "Zx Spectron" : "ZX Spectron",
  "Paw" : "PAW",
  "Judgement Of Anubis" : "Judgement of Anubis",
  "Blast From The Past" : "Blast From the Past",
  "Moon In Libra" : "Moon in Libra",
  "Death By Puppy" : "Death by Puppy",
  "Bi83 Spectrum" : "BI83 Spectrum",
  "Panthera Onca" : "Panthera onca",
  "Pink Ddpat" : "Pink DDPAT",
  "Swag-7" : "SWAG-7",
  "Jungle Ddpat" : "Jungle DDPAT",
  "Metallic Ddpat" : "Metallic DDPAT",
  "Colony Iv" : "Colony IV",
  "O.s.i.p.r." : "O.S.I.P.R.",
  "Red Fragcam" : "Red FragCam",
  "Legion Of Anubis" : "Legion of Anubis",
  "Pop Awp" : "POP AWP",
  "X-ray" : "X-Ray",
  "Desert-strike" : "Desert-Strike",
  "Boom" : "BOOM",
  "Neo-noir" : "Neo-Noir",
  "Re-entry" : "Re-Entry",
  "Blood In The Water" : "Blood in the Water",
  "Red Ddpat" : "Red DDPAT",
  "Run And Hide" : "Run and Hide"
}

weapon_map = {
  "Ak-47" : "AK-47",
  "Aug" : "AUG",
  "Awp" : "AWP",
  "Cz75-auto" : "CZ75-Auto",
  "Desert Eagle" : "Desert Eagle",
  "Dual Berettas" : "Dual Berettas",
  "Famas" : "FAMAS",
  "Five-seven" : "Five-SeveN",
  "G3sg1" : "G3SG1",
  "Galil Ar" : "Galil AR",
  "Glock-18" : "Glock-18",
  "M249" : "M249",
  "M4a1-s" : "M4A1-S",
  "M4a4" : "M4A4",
  "Mac-10" : "MAC-10",
  "Mag-7" : "MAG-7",
  "Mp5-sd" : "MP5-SD",
  "Mp7" : "MP7",
  "Mp9" : "MP9",
  "Negev" : "Negev",
  "Nova" : "Nova",
  "P2000" : "P2000",
  "P250" : "P250",
  "P90" : "P90",
  "Pp-bizon" : "PP-Bizon",
  "R8 Revolver" : "R8 Revolver",
  "Sawed-off" : "Sawed-Off",
  "Scar-20" : "SCAR-20",
  "Sg 553" : "SG 553",
  "Ssg 08" : "SSG 08",
  "Tec-9" : "Tec-9",
  "Ump-45" : "UMP-45",
  "Usp-s" : "USP-S",
  "Xm1014" : "XM1014"
}

wear_types = [
  "Factory New",
  "Minimal Wear",
  "Field-Tested",
  "Well-Worn",
  "Battle-Scarred"
]

rarities = {
  "Consumer Grade" : "Industrial Grade",
  "Industrial Grade" : "Mil-Spec Grade",
  "Mil-Spec Grade" : "Restricted",
  "Restricted" : "Classified",
  "Classified" : "Covert",
}

float_values = {
  "Factory New" : (0, 0.07),
  "Minimal Wear" : (0.07, 0.15),
  "Field-Tested" : (0.15, 0.38),
  "Well-Worn" : (0.38, 0.45),
  "Battle-Scarred" : (0.45, 1) 
}
